--- 
title: "A short guide to using British Library Newspaper Data, using R"
author: "Yann Ryan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [r_for_news.bib]
csl: mhra.csl
github-repo: yannryanBL/r-for-news-data
description: "This is a handbook to help new and existing users find, process and analyse historical newspaper data, using the programming language R, and its IDE R-Studio"
---

# Preface & Acknowledgements

I spent the last year or so working at the British Library as a Curator of Newspaper Data. It was an experimental position, conceived on the premise that the _data_ generated by newspaper digitisation projects, in this case the _Heritage Made Digital_ project, deserves its own curatorial role and set of practices.

It was an exciting time to work on such a project while 'big data' analysis using newspaper content, by historians, is no longer in its infancy, it is firmly in a soul-searching adolescence, and it's been exciting working on an evolving discipline, one which is developing its own set of practices, understanding where and how its bias works and the implications this might have, and generally moving from a sense of naive optimism to a practice which is more academically and mathematically rigorous and self-reflective. 

This book aims to give basic handbook for those who would like to dip their toes into big data analysis but don't know where to begin. It takes advantage of the fact that for the first time, newspaper data from British Library is available to download, in bulk and for free. It uses some of that data, walking through the process from its download to running basic DH analyses: word frequencies, sentiment analysis, topic modelling and text reuse detection. It also introduces some mapping techniques, again using a dataset produced and made available by the British Library: a metadata list of the newspaper collection, which we hope will be of use to a wide variety of researchers. 